[tool.poetry]
name = "proyecto_FLASalejandro"
version = "0.1.0"
description = "Descripción de mi proyecto."
authors = ["Alejandro <alealbaladejo29s@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.9"
flask = "^2.0.0"
requests = "^2.26.0"
